nome = str(input('Digite seu nome completo ')).strip()
div = nome.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(div[0]))
print('Seu ultimo nome é {}'.format(div[len(div)-1]))